version: '2'
template:
  name: Upgrade to Toolchain
  description: |2-
     A toolchain is an open, extensible system of tools that supports the development, deployment, and operations of an application.


    #### About the Upgrade Process
     When you create this toolchain, it is preconfigured with IBM Whitewater GitHub Enterprise for source control, Delivery Pipeline for building and deployment, and the Eclipse Orion Web IDE for code editing. You can add more tools to the toolchain as needed. To get started, click **Create**.


    #### More Info
     [Tutorial: Upgrade your project to a toolchain](https://ibm.biz/ids-upgrade-blogpost)

     [Docs: Getting started with Continuous Delivery](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/index.html)

     [Blog: Bluemix Continuous Delivery](https://www.ibm.com/blogs/bluemix/2016/11/bluemix-continuous-delivery-is-now-live/)
     
  header: '![](toolchain.svg)'
  required:
    - repo
toolchain:
  template:
    v1-projectId: '{{projectId}}'
    scheduledDate: '{{scheduledDate}}'
    v1-pipelineStages: '{{v1PipelineStages}}'
    v1-projectName: '{{v1ProjectName}}'
    v1-ProjectPublicVisibility: '{{v1ProjectPublicVisibility}}'
    getting_started: >-
      This toolchain was created from your [DevOps Services
      project]({{projectUrl}}). Migration of artifacts from the project to the tools in the toolchain continues 
      for a while after the toolchain is created. Before you use the toolchain, verify the status of the upgrade 
      by reviewing the banner on the [project page]({{projectUrl}}), then refer to [these steps](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/upgrade_projects.html#upgrade_next_steps) 
      for what to do next. To learn more about toolchains, see [Getting started with Continuous
      Delivery](https://console.ng.bluemix.net/docs/services/ContinuousDelivery/index.html?pos=2).

  name: '{{projectName}}'
  generator: migration-engine
services:
  repo:
    service_id: github_integrated
    parameters:
      repo_name: '{{form.github_integrated.parameters.repo_name}}'
      repo_url: ''
      type: new
      has_issues: true
      private_repo: true
      enable_traceability: '{{form.github_integrated.parameters.enable_traceability}}'
      legal: '{{form.github_integrated.parameters.legal}}'
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{projectName}}'
      v1-projectId: '{{projectId}}'
      configuration:
        content: '{{pipelineContent}}'
        execute: false
        env:
          REPO: repo
        source:
          version: v1
          environment: '{{pipelineEnv}}'
          pipelineUrl: '{{pipelineUrl}}'
          projectUrl: '{{projectUrl}}'
          showLink: true
  webide:
    service_id: orion
form:
  github_integrated:
    parameters:
      repo_name: '{{repoName}}'
      existing_repo_url: '{{projectRepoUrl}}'
      private_repo: '{{privateRepo}}'
      enable_traceability: false
      legal: false
    schema:
      $ref: github.json
