version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  required:
    - repo
toolchain:
  template:
    v1-projectId: '{{projectId}}'
    scheduledDate: '{{scheduledDate}}'
    v1-pipelineStages: '{{v1PipelineStages}}'
    getting_started:
      $ref: "#/messages/template.gettingStarted"
  name: '{{projectName}}'
  generator: migration-engine
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{projectName}}'
      repo_url: '{{projectRepoUrl}}'
      type: link
      has_issues: true
      enable_traceability: false
      track_and_plan:
        query: '{{form.githubpublic.parameters.query}}'
        labels: '{{form.githubpublic.parameters.labels}}'
        migrateTAndP: '{{form.githubpublic.parameters.migrateTAndP}}'
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{projectName}}'
      v1-projectId: '{{projectId}}'
      configuration:
        content: '{{pipelineContent}}'
        execute: false
        env:
          REPO: repo
        source:
          version: v1
          environment: '{{pipelineEnv}}'
          pipelineUrl: '{{pipelineUrl}}'
          projectUrl: '{{projectUrl}}'
          showLink: true
  webide:
    service_id: orion
form:
  githubpublic:
    parameters:
      repo_url: '{{projectRepoUrl}}'
      existing_repo_url: '{{projectRepoUrl}}'
      enable_traceability: false
      migrateTAndP: '{{migrateTAndP}}'
      query: ""
      labels:
        type: true
        severity: true
        state: true
        priority: true
        resolution: true
        filedAgainst: true
        tags: true
    schema:
      $ref: github.json
